# Generated by Django 5.1.3 on 2024-11-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResizableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='resized_images/')),
            ],
        ),
    ]
