# Generated by Django 5.1.3 on 2024-11-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_image', models.CharField(max_length=255)),
                ('resized_small_image', models.CharField(blank=True, max_length=255, null=True)),
                ('resized_medium_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
